
volumes:
  node_modules:
    driver: local


services:
  clinic-square-api:
    build: ./
    container_name: clinic-square-api
    ports:
      - "8001:8001"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    tty: true
    
